version: '2'
services:
  livy:
    image: tobby48/spark-livy:0.3_2.1
    volumes:
      - ./logs/livy:/apps/livy/logs
      - ./conf/livy.conf:/apps/livy/conf/livy.conf
      - ./jars:/apps/spark-modules
    ports:
      - "8998:8998"

  spark-master:
    image: bde2020/spark-master:2.1.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.1.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:2.1.1-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"